use_default_settings: true

search:
  safe_search: 0
  autocomplete: ""
  default_lang: ""

server:
  secret_key: "ci-domain-discovery-secret"
  limiter: false
  image_proxy: false

engines:
  - name: google
    engine: google
    shortcut: g
    disabled: false
  - name: bing
    engine: bing
    shortcut: b
    disabled: false
  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    disabled: false
  - name: brave
    engine: brave
    shortcut: br
    disabled: false
  - name: qwant
    engine: qwant
    shortcut: qw
    disabled: false
  - name: startpage
    engine: startpage
    shortcut: sp
    disabled: false
